<template>
  <v-container>
    <v-row>
      <v-col cols="12">
        <v-card>
          <v-card-title>Two-Factor Authentication Setup</v-card-title>
          <v-card-text>
            <v-alert v-if="message" :type="messageType" class="mb-4">
              {{ message }}
            </v-alert>

            <!-- If 2FA is not enabled -->
            <div v-if="!twoFAEnabled">
              <p class="mb-4">To enable two-factor authentication, you need to:</p>
              <ol>
                <li>Provide your email and password to generate the QR code</li>
                <li>Scan the QR code with an authenticator app (Google Authenticator, Authy, etc.)</li>
                <li>Enter the code generated by the app to validate</li>
              </ol>

              <v-form ref="qrForm" v-model="qrFormValid" class="mt-4">
                <v-text-field
                  v-model="qrEmail"
                  label="Email"
                  required
                  prepend-inner-icon="mdi-email"
                  :rules="emailRules"
                ></v-text-field>

                <v-text-field
                  v-model="qrPassword"
                  label="Password"
                  required
                  prepend-inner-icon="mdi-lock"
                  :type="showPassword ? 'text' : 'password'"
                  :append-inner-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                  @click:append-inner="showPassword = !showPassword"
                  :rules="passwordRules"
                ></v-text-field>

                <v-btn
                  :disabled="!qrFormValid || loadingQR"
                  :loading="loadingQR"
                  color="primary"
                  @click="generateQRCode"
                >
                  Generate QR Code
                </v-btn>
              </v-form>

              <!-- Display QR Code -->
              <div v-if="qrCodeUrl" class="mt-4 text-center">
                <p class="mb-2">Scan this QR code with your authenticator app:</p>
                <img :src="qrCodeUrl" alt="QR Code 2FA" style="max-width: 300px;" />
                
                <v-form ref="validateForm" v-model="validateFormValid" class="mt-4">
                  <v-text-field
                    v-model="validationCode"
                    label="6-digit code"
                    required
                    prepend-inner-icon="mdi-shield-lock"
                    maxlength="6"
                    :rules="codeRules"
                  ></v-text-field>

                  <v-btn
                    :disabled="!validateFormValid || loadingValidate"
                    :loading="loadingValidate"
                    color="success"
                    @click="validateCode"
                  >
                    Validate and Enable 2FA
                  </v-btn>
                </v-form>
              </div>
            </div>

            <!-- If 2FA is enabled -->
            <div v-else>
              <v-alert type="success" class="mb-4">
                2FA is enabled for your account.
              </v-alert>

              <v-form ref="settingsForm" v-model="settingsFormValid">
                <v-checkbox
                  v-model="require2FAForBasicLogin"
                  label="Require 2FA for email/password login"
                ></v-checkbox>

                <v-checkbox
                  v-model="require2FAForSocialLogin"
                  label="Require 2FA for social login"
                ></v-checkbox>

                <v-btn
                  :disabled="!settingsFormValid || loadingSettings"
                  :loading="loadingSettings"
                  color="primary"
                  @click="updateSettings"
                >
                  Save Settings
                </v-btn>
              </v-form>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { orionUsersService, extractOrionErrorMessage } from '../services/orionUsers';
import { authService } from '../services/auth';

export default {
  name: 'TwoFactorSettings',
  data() {
    return {
      twoFAEnabled: false, // TODO: Check actual 2FA status
      qrFormValid: false,
      validateFormValid: false,
      settingsFormValid: true,
      qrEmail: '',
      qrPassword: '',
      showPassword: false,
      qrCodeUrl: null,
      validationCode: '',
      require2FAForBasicLogin: false,
      require2FAForSocialLogin: false,
      loadingQR: false,
      loadingValidate: false,
      loadingSettings: false,
      message: null,
      messageType: 'info',
      emailRules: [
        v => !!v || 'Email is required',
        v => /.+@.+\..+/.test(v) || 'Email must be valid'
      ],
      passwordRules: [
        v => !!v || 'Password is required'
      ],
      codeRules: [
        v => !!v || 'Code is required',
        v => (v && v.length === 6) || 'Code must have 6 digits'
      ]
    };
  },
  methods: {
    async generateQRCode() {
      if (!this.$refs.qrForm.validate()) {
        return;
      }

      this.loadingQR = true;
      this.message = null;

      try {
        const blob = await orionUsersService.getQRCode(this.qrEmail, this.qrPassword);
        this.qrCodeUrl = URL.createObjectURL(blob);
        this.message = 'QR code generated successfully. Scan with your authenticator app.';
        this.messageType = 'success';
      } catch (error) {
        console.error('Error generating QR code:', error);
        this.message = extractOrionErrorMessage(error) || 'Error generating QR code. Check your credentials.';
        this.messageType = 'error';
      } finally {
        this.loadingQR = false;
      }
    },

    async validateCode() {
      if (!this.$refs.validateForm.validate()) {
        return;
      }

      this.loadingValidate = true;
      this.message = null;

      try {
        const response = await orionUsersService.validate2FA(
          this.qrEmail,
          this.qrPassword,
          this.validationCode
        );

        if (response.authentication && response.authentication.token) {
          // 2FA enabled successfully
          this.twoFAEnabled = true;
          this.message = '2FA enabled successfully!';
          this.messageType = 'success';
          this.qrCodeUrl = null;
          this.validationCode = '';
        } else {
          this.message = 'Invalid code. Please try again.';
          this.messageType = 'error';
        }
      } catch (error) {
        console.error('Error validating code:', error);
        this.message = extractOrionErrorMessage(error) || 'Invalid code. Please try again.';
        this.messageType = 'error';
      } finally {
        this.loadingValidate = false;
      }
    },

    async updateSettings() {
      this.loadingSettings = true;
      this.message = null;

      try {
        const token = authService.getToken();
        const user = authService.getUser();
        const email = user?.email || this.qrEmail;

        await orionUsersService.update2FASettings(
          email,
          this.require2FAForBasicLogin,
          this.require2FAForSocialLogin,
          token
        );

        this.message = 'Settings saved successfully!';
        this.messageType = 'success';
      } catch (error) {
        console.error('Error updating settings:', error);
        this.message = extractOrionErrorMessage(error) || 'Error saving settings.';
        this.messageType = 'error';
      } finally {
        this.loadingSettings = false;
      }
    }
  }
};
</script>

